### ISSUE TITLE
[Enigma] Оригинально

### ISSUE THREAD

**Issue by pavel-b-novikov** [sirgl/nsudotnet#2]
Это я про вашу идею со словарем делегатов. Однако во-первых. Вы умудрились продублировать код для словаря алгоритмов в экрипторе и декрипторе, за что вас проклянут коллеги, которым надо поправить энкриптор, после чего тестировщики им выкатят такой же баг, но про декриптор. Вынесете этот glue-код куда-нибудь в отдельный класс (можно даже статический). 

Второе: AlgorithmSuppliers[algorithm.ToLower()] - эта фигня не выдает null при отсутствии ключа, как вам бы того хотелось, а бросает Exception. Так что переделайте этот момент. Заодно мне бы хотелось услышать ваши предположения почему в .NET Framework сделано именно так, а не иначе.

**Comment by sirgl** [comment]
Изначально предполагалось, что списки алгоритмов шифрования и дешифрирования могут различаться. По большому счету, программа состоит из двух абсолютно разных частей: шифровщика и дешифровщика.

Dictionary может хранить не только reference-типы, так что нет запрещенного значения для всех типов.

Пофиксил.
