### ISSUE TITLE
[Enigma] Secret

### ISSUE THREAD

**Issue by pavel-b-novikov** [sirgl/nsudotnet#3]
Из каких соображений он сделан структурой?

**Comment by sirgl** [comment]
Чтобы возвращать было удобно, а не через out или ref

**Comment by pavel-b-novikov** [comment]
Простите, что? О_о

**Comment by sirgl** [comment]
А, видимо, вопрос не так понял. Это вышло случайно:) На плюсах параллельно писал, вот data type так и сделал. Пофиксил.

**Comment by pavel-b-novikov** [comment]
Ладно, будем считать что я не читал первый комментарий
