### ISSUE TITLE
[TicTacToe] Списано

### ISSUE THREAD

**Issue by pavel-b-novikov** [sirgl/nsudotnet#4]
Сначала я думал что мне кажется, но потом увидел, что вывод на консоль через DOS-овскую ASCII-графику я видел только у одного человека - у @dymova. Признавайтесь кто у кого списал

**Comment by dymova** [comment]
Так мы близко общаемся,  обсуждаем.  Через псевдографику он первый сделал

**Comment by pavel-b-novikov** [comment]
@dymova , @sirgl у вас еще WinConditions похожи. Отправить вас совместно пилить UI? До конца семестра еще время есть.

**Comment by dymova** [comment]
Может я лучше ещё какую-нибудь ещё задачу напишу? Только без ui,
пожалуйста
4 мая 2016 г. 2:25 PM пользователь "Pavel Novikov" <notifications@github.com>
написал:

**Comment by pavel-b-novikov** [comment]
@dymova Чего это так?

**Comment by dymova** [comment]
Я начинала делать на wpf +caliburn.micro к крестикам-ноликам gui ,  совсем
не понравилось

**Comment by sirgl** [comment]
Поддерживаю

**Comment by pavel-b-novikov** [comment]
А.. вы на последней лекции не были.

**Comment by pavel-b-novikov** [comment]
Есть вариант для ленивых: я просто делю оценку и раздаю по 3 балла обоим.

**Comment by sirgl** [comment]
Мы согласны

**Comment by pavel-b-novikov** [comment]
скучные вы
